### ISSUE TITLE
non-ASCII characters  => ArgumentOutOfRangeException: Index and count must refer to a location within the string

### ISSUE THREAD

**Issue by cda963** [Sergio0694/BinaryPack#27]
I'm getting the following error when trying to serialize certain objects:

```bash
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string. (Parameter 's')
   at System.Text.UTF8Encoding.GetBytes(String s, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex)
   at __IL__BinarySerializer`1_1(String , BinaryWriter& )
   at BinaryPack.BinaryConverter.Serialize[T](T obj)
```

**Comment by cojocaru-dragos-alexandru** [comment]
I just performed a simple test and indeed it seems that having strings with non-ASCII characters causes this error:

```csharp
using BinaryPack;
using System;

namespace BinaryPackTest
{
	class Program
	{
		static void Main(string[] args)
		{
			var obj = new Test();
			var serialized = BinaryConverter.Serialize(obj); // The error is thrown here
			Console.ReadLine();
		}
	}

	class Test
	{
		public string MyProperty { get; set; } = "Pastilă"; // the "ă" character causes the exception
	}
}
```

**Comment by CodeApex** [comment]
I am having this exact same issue.

cojocaru, have you had any luck figuring fixing it?

**Comment by cojocaru-dragos-alexandru** [comment]
> I am having this exact same issue.
> 
> cojocaru, have you had any luck figuring fixing it?

No, still not fixed...

**Comment by Sergio0694** [comment]
If I had to guess this is probably related to some incorrect handling of characters encoded with longer UTF-8 sequences [here](https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L22). As the disclaimer in the readme says, I'm not really maintaining this library anymore so I don't expect to fix this any time soon, but PRs are always welcome, and I'be happy to review and merge one if anyone wanted to have a look and fix this 😄

**Comment by cojocaru-dragos-alexandru** [comment]
Unfortunately stepping through the code in debug mode doesn't provide any hints. Maybe you could help.

**Comment by rootflood** [comment]
BinaryPack is aggressively fast and MessagePack is very well
but if you don't care about speed very much i have a srializer, this is a sample use of the [serializer](https://github.com/monsajem/Incs/tree/main/Tests/Datawork/Serialization) in my library

however the bug is like:
```C#
            var x = "Pastilă";
            var ArrayLen = Encoding.UTF8.GetByteCount(x.AsSpan());
            var array = new byte[ArrayLen];
            var StrLen = ArrayLen; //bug
            Encoding.UTF8.GetBytes(x, 0, StrLen, array, 0);
```

here:
https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L73

**Comment by cojocaru-dragos-alexandru** [comment]
> BinaryPack is aggressively fast and MessagePack is very well
> but if you don't care about speed very much i have a srializer, this is a sample use of the [serializer](https://github.com/monsajem/Incs/tree/main/Tests/Datawork/Serialization) in my library
> 
> however the bug is like:
> 
> ```cs
>             var x = "Pastilă";
>             var ArrayLen = Encoding.UTF8.GetByteCount(x.AsSpan());
>             var array = new byte[ArrayLen];
>             var StrLen = ArrayLen; //bug
>             Encoding.UTF8.GetBytes(x, 0, StrLen, array, 0);
> ```
> 
> here:
> https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L73

Thanks for the info, but personally I haven't been able to find a fix for this bug. We really love the speed of this library, but this bug makes it unusable in production for us :(

**Comment by cojocaru-dragos-alexandru** [comment]
> If I had to guess this is probably related to some incorrect handling of characters encoded with longer UTF-8 sequences [here](https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L22). As the disclaimer in the readme says, I'm not really maintaining this library anymore so I don't expect to fix this any time soon, but PRs are always welcome, and I'be happy to review and merge one if anyone wanted to have a look and fix this 😄

Do you suppose you can find a bit of time and try to have this issue fixed? I need to push some code in production and this bug is a big no-no at the moment, and we really want to use this library because of it's great speed.

**Comment by Sergio0694** [comment]
> "but this bug makes it unusable in production for us :("

@cojocaru-dragos-alexandru just for clarity, allow me to point out that:

- The readme of this repo explicitly says this library is lo longer maintained, is provided as-is, and isn't tested for production
- You claim you're using this library in production, yet you or your company aren't sponsoring this library at all. This isn't how you help build a healthy OSS community, and you shouldn't really expect maintainers to work for free fixing bugs for libraries that are being used by company without even giving credit back to authors. This is an issue with OSS in general, with companies just expecting maintainers to do unpaid work to maintain libraries they rely on as if they had some support contract in place.
- I would still be willing to take a look at PRs if anyone wanted to jump in and fix that bit. @rootflood already identified where the bug is, it's just a matter of patching that bit of codegen to address the incorrect charset decoding there. I don't have time to work on this right now between work, other personal projects I'm maintaining, and just having some personal time as well (and to be honest, updating `BinaryPack` is really down in my priorities list), but anyone's welcome to jump in. I can't guarantee I'll find the time to review and merge PRs immediately, but I will definitely take a look at some point 😄

Cheers!

**Comment by sylveon** [comment]
If it's *that* much of a blocking issue, certainly you could justify the time to fix the issue and make a PR to your employer.

**Comment by rootflood** [comment]
i think use this lines and replace to that buggy line could fix it

buggy code:
https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L73

fix via replace that buggy code to:
https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L35-L36

**Comment by lm-adruschel** [comment]
> i think use this lines and replace to that buggy line could fix it
> 
> buggy code:
> 
> https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L73
> 
> fix via replace that buggy code to:
> 
> https://github.com/Sergio0694/BinaryPack/blob/6bc76af0b8462c9196244a1a106dd8f0e2a0dd6d/src/BinaryPack/Serialization/Processors/StringProcessor.cs#L35-L36

I'm not very familiar with IL coding. Can you please help with some more clear words what you recommend?

Which part should be replaced with what code?

Thanks a lot for your efforts.
